[package]
name = "spark-script"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
description = "Spark 脚本引擎（Oaks Valkyrie → spark-vm）"
keywords = ["spark", "script", "valkyrie"]
categories = ["game-development"]
publish = false

[dependencies]
spark-core = { workspace = true }
spark-gc = { workspace = true }
spark-vm = { workspace = true }
spark-jit = { workspace = true }
oak-core = { workspace = true }
oak-valkyrie = { workspace = true }
thiserror = { workspace = true }
