[package]
name = "spark-app"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
description = "Spark 应用壳与演示入口"
keywords = ["spark", "app"]
categories = ["game-development"]
publish = false

[[bin]]
name = "spark"
path = "src/main.rs"

[dependencies]
spark-core = { workspace = true }
spark-ecs = { workspace = true }
spark-time = { workspace = true }
spark-event = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
