[workspace]
resolver = "2"
members = [
    "projects/engine/*",
    "projects/bindings/*",
]
default-members = [
    "projects/bindings/spark-app",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Aster <192607617@qq.com>"]
license = "Apache-2.0"
readme = "readme.md"

[workspace.dependencies]
spark-core = { path = "projects/engine/spark-core" }
spark-ecs = { path = "projects/engine/spark-ecs" }
spark-time = { path = "projects/engine/spark-time" }
spark-event = { path = "projects/engine/spark-event" }
spark-input = { path = "projects/engine/spark-input" }
spark-shader = { path = "projects/engine/spark-shader" }
spark-render = { path = "projects/engine/spark-render" }
spark-app = { path = "projects/bindings/spark-app" }
thiserror = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
wgpu = { version = "26", default-features = true }
winit = "0.30"
pollster = "1"
bytemuck = { version = "1", features = ["derive"] }
fontdue = "0.9"

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
