[package]
name = "spark-video"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
description = "Spark 视频：解复用与包泵（Symphonia via spark-media）"
keywords = ["spark", "video", "symphonia"]
categories = ["game-development", "multimedia"]
publish = false

[dependencies]
spark-types = { workspace = true }
spark-media = { workspace = true }
tracing = { workspace = true }
