[package]
name = "spark-widget"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
description = "Spark Widget 系统：Ui 上下文、布局、主题、动效与基础控件"
keywords = ["spark", "widget"]
categories = ["game-development", "gui"]
publish = false

[dependencies]
spark-core = { workspace = true }
spark-input = { workspace = true }
spark-renderer = { workspace = true }
spark-localization = { workspace = true }
