[package]
name = "spark-animator"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
description = "动画数据、单段播放与状态控制。不绘制、不上传纹理"
keywords = ["spark", "animation", "animator"]
categories = ["game-development"]
publish = false

[dependencies]
spark-core = { workspace = true }
spark-geometry = { workspace = true }
spark-ecs = { workspace = true }
