[package]
name = "spark-script-valkyrie"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
description = "Spark 脚本前端：Oaks Valkyrie AST → spark-ir HIR"
keywords = ["spark", "script", "valkyrie"]
categories = ["game-development"]
publish = false

[dependencies]
spark-diagnostics = { workspace = true }
spark-vm = { workspace = true }
spark-gc = { workspace = true }
spark-ir = { workspace = true }
oak-core = { workspace = true }
oak-valkyrie = { workspace = true }
