[package]
name = "spark-debugger"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
description = "Spark 调试绘制、帧统计与检查器钩子"
keywords = ["spark", "debug"]
categories = ["game-development"]
publish = false

[dependencies]
spark-types = { workspace = true }
spark-renderer = { workspace = true }
