[package]
name = "spark-script-lua"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
description = "Spark 脚本前端：Oaks Lua → spark-vm 字节码"
keywords = ["spark", "script", "lua"]
categories = ["game-development"]
publish = false

[dependencies]
spark-diagnostics = { workspace = true }
spark-gc = { workspace = true }
spark-ir = { workspace = true }
spark-script-valkyrie = { workspace = true }
spark-vm = { workspace = true }
oak-core = { workspace = true }
oak-lua = { workspace = true }
