[package]
name = "spark-ir"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
description = "Spark 语言无关 IR（HIR / MIR / LIR）与字节码生成"
keywords = ["spark", "script", "ir"]
categories = ["game-development"]
publish = false

[dependencies]
spark-diagnostics = { workspace = true }
spark-gc = { workspace = true }
spark-vm = { workspace = true }
