[package]
name = "spark-png"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
description = "Spark PNG 解码 → TextureUpload"
keywords = ["spark", "png", "texture", "format"]
categories = ["game-development", "parsing"]
publish = false

[dependencies]
spark-core = { workspace = true }
spark-texture = { workspace = true }
image = { version = "0.25", default-features = false, features = ["png"] }

[dev-dependencies]
image = { version = "0.25", default-features = false, features = ["png"] }
