[package]
name = "spark-png"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
description = "Spark PNG 解码/编码 → TextureUpload（pure Rust `png`）"
keywords = ["spark", "png", "texture", "format"]
categories = ["game-development", "parsing"]
publish = false

[dependencies]
spark-core = { workspace = true }
spark-texture = { workspace = true }
png = { workspace = true }
